kind = "web"
previewPath = "/"
title = "Monitor Giełdowy"
version = "1.0.0"
id = "artifacts/stock-monitor"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24283

[services.development]
run = "pnpm --filter @workspace/stock-monitor run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/stock-monitor", "run", "build" ]
publicDir = "artifacts/stock-monitor/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24283"
BASE_PATH = "/"
